source 'https://rubygems.org'

# https://github.com/plataformatec/simple_form
# https://github.com/twbs/bootstrap-sass


#Core Libraries
gem 'rails', '4.2.3'
gem 'sqlite3'
# gem 'unicorn'

#Front End Tools
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'simple_form'


#Debugging & Test Suite
group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
end

group :development do
  gem 'spring'
end

#Other
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
